jaxen: Do not build an all PACKAGE_ARCH
jaxen depends on non -native recipes and breaks multiconfig.

Fixes:

| 138 problems (138 warnings)rm: cannot remove 'build/org/jdom/input': Directory not empty
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_compile (log file is located at /workdir/build/tmp/work/all-poky-linux/jaxen/1.1.6-r0/temp/log.do_compile.21778)
NOTE: recipe jaxen-1.1.6-r0: task do_compile: Failed
ERROR: Task (multiconfig:inteli7:/workdir/repo/poky/../meta-java/recipes-core/xml-commons/jaxen_1.1.6.bb:do_compile) failed with exit code '1'

Signed-off-by: Ricardo Ribalda Delgado <ricardo@ribalda.com>