bsf: Do not build as all PACKAGE_ARCH
The package DEPENDS on non -native package, which breaks multiconfig.

Fixes:

NOTE: recipe bsf-2.4.0-r1: task do_package: Succeeded
ERROR: mc:qt5507:bsf-2.4.0-r1 do_package: Error executing a python function in exec_python_func() autogenerated:

The stack trace of python calls that resulted in this exception/failure was:
File: 'exec_python_func() autogenerated', lineno: 2, function: <module>
     0001:
 *** 0002:populate_packages(d)
     0003:
File: '/workdir/repo/poky/meta/classes/package.bbclass', lineno: 1237, function: populate_packages
     1233:
     1234:            mkdir_recurse(dvar, root, os.path.dirname(file))
     1235:            fpath = os.path.join(root,file)
     1236:            if not cpath.islink(file):
 *** 1237:                os.link(file, fpath)
     1238:                continue
     1239:            ret = bb.utils.copyfile(file, fpath)
     1240:            if ret is False or ret == 0:
     1241:                bb.fatal("File population failed")
Exception: FileExistsError: [Errno 17] File exists: './usr/share/java/bsf-2.4.0.jar' -> '/workdir/build/tmp/work/all-poky-linux/bsf/2.4.0-r1/packages-split/libbsf-java/./usr/share/java/bsf-2.4.0.jar'

ERROR: mc:qt5507:bsf-2.4.0-r1 do_package: [Errno 17] File exists: './usr/share/java/bsf-2.4.0.jar' -> '/workdir/build/tmp/work/all-poky-linux/bsf/2.4.0-r1/packages-split/libbsf-java/./usr/share/java/bsf-2.4.0.jar'
ERROR: mc:qt5507:bsf-2.4.0-r1 do_package: Function failed: populate_packages
ERROR: Logfile of failure stored in: /workdir/build/tmp/work/all-poky-linux/bsf/2.4.0-r1/temp/log.do_package.12673
NOTE: recipe bsf-2.4.0-r1: task do_package: Failed
ERROR: Task (multiconfig:qt5507:/workdir/repo/poky/../meta-java/recipes-core/jakarta-libs/bsf_2.4.0.bb:do_package) failed with exit code '1'

Signed-off-by: Ricardo Ribalda Delgado <ricardo@ribalda.com>