icedtea7: Add missing DEPENDS
Fixes:
| checking X11/X.h usability... no
| checking X11/X.h presence... no
| checking for X11/X.h... no
| configure: error: "xorg headers were not found -
| 	try installing xorg-x11-proto-devel."
| NOTE: The following config.log files may provide further information.
| NOTE: /workdir/build/tmp/work/x86_64-linux/icedtea7-native/2.1.3-r1.0/icedtea-2.1.3/build/config.log
| ERROR: configure failed
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_configure (log file is located at /workdir/build/tmp/work/x86_64-linux/icedtea7-native/2.1.3-r1.0/temp/log.do_configure.29594)
ERROR: Task (/workdir/repo/poky/../meta-java/recipes-core/icedtea/icedtea7-native_2.1.3.bb:do_configure) failed with exit code '1'

Suggested-by: Jacob Kroon <jacob.kroon@mikrodidakt.se>
Signed-off-by: Ricardo Ribalda Delgado <ricardo@ribalda.com>