jlex: Do not build as an all PACKAGE_ARCH
jlex RDEPENDS on non -all package and breaks multiconfig.

Fixes:

ERROR: mc:qt5506:jlex-1.2.6-r0 do_package_write_deb: Fatal errors occurred in subprocesses:
Command 'PATH="/workdir/build/tmp/sysroots-uninative/x86_64-linux/usr/bin:/workdir/repo/poky/scripts:/workdir/build/tmp/work/all-poky-linux/jlex/1.2.6-r0/recipe-sysroot-native/usr/bin/allarch-poky-linux:/workdir/build/tmp/work/all-poky-linux/jlex/1.2.6-r0/recipe-sysroot/usr/bin/crossscripts:/workdir/build/tmp/work/all-poky-linux/jlex/1.2.6-r0/recipe-sysroot-native/usr/sbin:/workdir/build/tmp/work/all-poky-linux/jlex/1.2.6-r0/recipe-sysroot-native/usr/bin:/workdir/build/tmp/work/all-poky-linux/jlex/1.2.6-r0/recipe-sysroot-native/sbin:/workdir/build/tmp/work/all-poky-linux/jlex/1.2.6-r0/recipe-sysroot-native/bin:/workdir/repo/poky/bitbake/bin:/workdir/build/tmp/hosttools" dpkg-deb -b /workdir/build/tmp/work/all-poky-linux/jlex/1.2.6-r0/packages-split/jlex /workdir/build/tmp/work/all-poky-linux/jlex/1.2.6-r0/deploy-debs/all' returned non-zero exit status 2
Subprocess output:dpkg-deb: building package 'jlex' in '/workdir/build/tmp/work/all-poky-linux/jlex/1.2.6-r0/deploy-debs/all'.
dpkg-deb: error: unable to create '/workdir/build/tmp/work/all-poky-linux/jlex/1.2.6-r0/deploy-debs/all': No such file or directory

ERROR: mc:qt5506:jlex-1.2.6-r0 do_package_write_deb:
ERROR: mc:qt5506:jlex-1.2.6-r0 do_package_write_deb: Function failed: do_package_deb
ERROR: Logfile of failure stored in: /workdir/build/tmp/work/all-poky-linux/jlex/1.2.6-r0/temp/log.do_package_write_deb.1491

Signed-off-by: Ricardo Ribalda Delgado <ricardo@ribalda.com>