jdom: Do not use all as PACKAGE_ARCH
It DEPENDS on packages that are not -native.

Fixes:

ERROR: mc:qt5506:jdom-1.1.3-r0 do_package: Package already staged (/workdir/build/tmp/sstate-control/manifest-allarch-jdom.package)?!
ERROR: mc:qt5506:jdom-1.1.3-r0 do_package:
ERROR: mc:qt5506:jdom-1.1.3-r0 do_package: Function failed: sstate_task_postfunc
ERROR: Logfile of failure stored in: /workdir/build/tmp/work/all-poky-linux/jdom/1.1.3-r0/temp/log.do_package.5632

Signed-off-by: Ricardo Ribalda Delgado <ricardo@ribalda.com>